/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dt_instance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        dt_instance classUnderTest = new dt_instance();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
